# docker-compose.yml
version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  backend:
    build: .
    volumes:
      - .:/app
    ports:
      - "3333:3333"
    depends_on:
      - db
    environment:
      PG_PASSWORD: password
  frontend:
    build: ./frontend/
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"
    command: yarn start
    depends_on:
      - backend
    # links:
    #   - backend
    # tty: true
    # stdin_open: true
